name: freezed_example
description: A sample command-line application.
version: 1.0.0
environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  freezed_annotation: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.10
  freezed: ^1.1.1
  lints: ^1.0.0
  test: ^1.16.0
